import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { Main, ProductContainer } from '../styles/pages';
import WineLogo from '../assets/black.svg';
import Navbar from '../components/Navbar';
import { Product } from '../types/Products';
import { ProductItem } from '../components/ProductItem';
import FilterByPrice from '../components/FilterByPrice';

export default function Home({ list }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      {/* <div>
        <WineLogo />
      </div> */}

      <Main>
        <FilterByPrice />
        <ProductContainer>
          <p>
            <span>{list.length}</span> produtos encontrados
          </p>

          <ul>
            {list.map((item: Product) => (
              <ProductItem key={item.id} items={item} />
            ))}
          </ul>
        </ProductContainer>
      </Main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const limit = query.limit;
  const page = query.page;

  const response = await fetch(
    `https://wine-back-test.herokuapp.com/products?page&limit=10`
  );

  const data = await response.json();

  return {
    props: {
      list: data.items,
    },
  };
};
